[versions]
agp = "8.13.0"
hiltNavigationFragment = "1.3.0"
kotlin = "2.2.20"
core = "1.17.0"

coreKtx = "1.17.0"
appcompat = "1.7.1"
lifecycleViewmodelSavedstate = "2.9.4"
material = "1.13.0"
activity = "1.11.0"
constraintlayout = "2.2.1"
fragmentKtx = "1.8.9"
recyclerview = "1.4.0"

mapsMobile = "4.3.1-lite"

lifecycleViewmodelKtx = "2.9.4"

firebaseBom = "34.3.0"
firebaseDatabaseKtx = "21.0.0"
firebaseAuthKtx = "23.2.1"
firebaseStorageKtx = "21.0.2"
firebasePerfKtx = "21.0.5"
firebaseInstallations = "19.0.1"

playServicesLocation = "21.3.0"
playServicesMaps = "19.2.0"

navigationFragmentKtx = "2.9.5"
securityCrypto = "1.1.0"
tinkAndroid = "1.18.0"
voiceSdk = "4.6.0"
workRuntimeKtx = "2.10.5"

kotlinxCoroutinesAndroid = "1.10.2"
kotlinxMetadataJvm = "0.9.0"

zxingAndroidEmbedded = "4.3.0"
livekitAndroid = "2.20.2"

hiltAndroid = "2.57.2"

junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-hilt-navigation-fragment = { module = "androidx.hilt:hilt-navigation-fragment", version.ref = "hiltNavigationFragment" }
androidx-lifecycle-viewmodel-savedstate = { module = "androidx.lifecycle:lifecycle-viewmodel-savedstate", version.ref = "lifecycleViewmodelSavedstate" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }

androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifecycle-livedata-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleViewmodelKtx" }

firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-database-ktx = { group = "com.google.firebase", name = "firebase-database-ktx", version.ref = "firebaseDatabaseKtx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version.ref = "firebaseAuthKtx" }
firebase-storage-ktx = { group = "com.google.firebase", name = "firebase-storage-ktx", version.ref = "firebaseStorageKtx" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx", version.ref = "firebasePerfKtx" }
firebase-installations = { group = "com.google.firebase", name = "firebase-installations", version.ref = "firebaseInstallations" }

play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }
play-services-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "playServicesMaps" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationFragmentKtx" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-metadata-jvm = { group = "org.jetbrains.kotlinx", name = "kotlinx-metadata-jvm", version.ref = "kotlinxMetadataJvm" }

tink-android = { module = "com.google.crypto.tink:tink-android", version.ref = "tinkAndroid" }
voice-sdk = { module = "io.agora.rtc:voice-sdk", version.ref = "voiceSdk" }
zxing-android-embedded = { module = "com.journeyapps:zxing-android-embedded", version.ref = "zxingAndroidEmbedded" }
livekit-android = { module = "io.livekit:livekit-android", version.ref = "livekitAndroid" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hiltAndroid" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

mapsMobile = { module = "com.yandex.android:maps.mobile", version.ref = "mapsMobile" }

core = { module = "androidx.core:core", version.ref = "core" }


[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hiltAndroid" }
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version = "2.1.21-2.0.1" }
com-google-gms-google-services = { id = "com.google.gms.google-services", version = "4.4.2" }
